Drop database if exists apparelHub;

CREATE DATABASE apparelHub;

USE apparelHub;

CREATE TABLE user(

userName VARCHAR (50),
passWord VARCHAR(50)
);

CREATE TABLE buyer(
B_id VARCHAR (10) PRIMARY KEY,
name VARCHAR(50),
address TEXT,
telNum INT(20)
);

CREATE TABLE Payment(
Pay_id VARCHAR (10) PRIMARY KEY,
amount DOUBLE(7,2),
status VARCHAR(20)
);

CREATE TABLE orders(
orderId VARCHAR (10) PRIMARY KEY,
B_id VARCHAR (10),
Pay_id VARCHAR(10),
price DOUBLE(10,2),
Description VARCHAR(100),
Qty INT (10),
Date DATE,
CONSTRAINT FOREIGN KEY(B_id) REFERENCES buyer (B_id) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FOREIGN KEY(Pay_id) REFERENCES Payment (Pay_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Stock(
St_id VARCHAR (10) PRIMARY KEY,
Type VARCHAR (50),
Amount INT (15),
Description VARCHAR(75)
);

CREATE TABLE Supplier(
Sup_id VARCHAR (10) PRIMARY KEY,
Name VARCHAR(20),
Address TEXT,
telNum INT(20)
);

CREATE TABLE StockSupplierDetail(
St_id VARCHAR(10),
Sup_id VARCHAR (10),
CONSTRAINT FOREIGN KEY(St_id) REFERENCES Stock(St_id) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FOREIGN KEY(Sup_id) REFERENCES Supplier(Sup_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Employee(
Emp_id VARCHAR(10) PRIMARY KEY,
Name VARCHAR (50),
telNum INT(20),
Address TEXT

);

CREATE TABLE Attendance(
8hour TIME,
OT TIME,
ShortLeave TIME,
Emp_id VARCHAR (10),
CONSTRAINT FOREIGN KEY(Emp_id) REFERENCES Employee(Emp_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Category(
Emp_type ENUM('Worker','Helper'),
Emp_id VARCHAR (10),
CONSTRAINT FOREIGN KEY(Emp_id) REFERENCES Employee(Emp_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Salary(
Amount DOUBLE (7,2),
date DATE,
Emp_id VARCHAR (10),
CONSTRAINT FOREIGN KEY(Emp_id) REFERENCES Employee(Emp_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Schedule(
Sch_id VARCHAR (10) PRIMARY KEY,
Description VARCHAR (100),
Emp_id VARCHAR (10),
CONSTRAINT FOREIGN KEY(Emp_id) REFERENCES Employee(Emp_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Product(
Pr_id VARCHAR (10) PRIMARY KEY,
TotalAmount INT(10),
Description VARCHAR(50)
);

CREATE TABLE Output(
Output_id VARCHAR (10) PRIMARY KEY,
Count INT (15),
Pr_id VARCHAR(10),
CONSTRAINT FOREIGN KEY(Pr_id) REFERENCES Product(Pr_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ScheduleOutputDetail(
Sch_id VARCHAR (10) ,
Output_id VARCHAR(10),
CONSTRAINT FOREIGN KEY(Sch_id) REFERENCES Schedule(Sch_id) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FOREIGN KEY(Output_id) REFERENCES Output (Output_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Machine(
M_id VARCHAR(10) PRIMARY KEY,
Type VARCHAR(20),
Cost DOUBLE (7,2)
);
